Repository FrangipaneTeam/terraform-plugin-framework-supertypes, pull requests merged in 2023-07, with the labels that each got.

#5 chore: first release
  .changelog/4.txt
  .vscode/changelog.code-snippets
Labels: Chore, size/S

#6 ci: fix generate changelog
  .github/workflows/generate_changelog.yml
Labels: CI, size/XS

#8 chore: first release
  .changelog/4.txt
Labels: Chore, size/XS

#10 fix: simple templates
  bool_type.go
  bool_value.go
  float64_type.go
  float64_value.go
  int64_type.go
  int64_value.go
  number_type.go
  number_value.go
  string_type.go
  string_value.go
  templates/simple_type.go.tmpl
  templates/simple_value.go.tmpl
Labels: CI, category/generate, size/S, Fix

#11 test: add unit tests
  bool_type.go
  bool_type_test.go
  bool_value.go
  bool_value_test.go
  float64_type.go
  float64_type_test.go
  float64_value.go
  float64_value_test.go
  go.mod
  go.sum
  int64_type.go
  int64_type_test.go
  int64_value.go
  int64_value_test.go
  list_type.go
  list_type_test.go
  list_value.go
  list_value_test.go
  map_type.go
  map_type_test.go
  map_value.go
  map_value_test.go
  missing.go
  number_type.go
  number_type_test.go
  number_value.go
  number_value_test.go
  object_type_test.go
  object_value_test.go
  pointer_test.go
  set_type.go
  set_type_test.go
  set_value.go
  set_value_test.go
  string_type.go
  string_type_test.go
  string_value.go
  string_value_test.go
  template.go
  templates/array_type.go.tmpl
  templates/array_value.go.tmpl
  templates/simple_type.go.tmpl
  templates/simple_value.go.tmpl
Labels: CI, Chore, size/XL, category/generate, Test

#12 fix: custom funcs
  bool_value.go
  float64_value.go
  int64_value.go
  number_value.go
  object_value.go
  string_value.go
  template.go
  templates/object_value.go.tmpl
  templates/simple_value.go.tmpl
Labels: size/S, Fix

#13 fix: object/singleNested value
  .github/workflows/go-generate.yml
  object_value.go
  single_nested_value.go
  templates/object_value.go.tmpl
  templates/single_nested_value.go.tmpl
Labels: size/XS, Fix

#14 fix: nested value
  list_nested_value.go
  map_nested_value.go
  set_nested_value.go
  templates/nested_value.go.tmpl
Labels: size/XS, Fix

#16 fix: nested value
  list_nested_value.go
  map_nested_value.go
  set_nested_value.go
  templates/nested_value.go.tmpl
Labels: size/XS, Fix

#18 chore: Add test linter when go-generate is running
  .github/workflows/go-generate.yml
  .github/workflows/tests.yml
Labels: Chore, size/XS

#20 fix: go generate workflow with test linter workflow
  .github/workflows/go-generate.yml
Labels: CI, size/XS, Fix
